import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Layout from "@/components/common/Layout";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import SideNavbar from "@/components/common/SideNavbar";
import { Oswald } from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oswald.className}>
      <body className=" dark">
        <NextAuthProvider>
          <div className="flex h-screen">
            <main className="flex-1">
              <Layout>{children}</Layout>
            </main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
